[package]
name = "wp_query_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "24.0.0"
mysql_common = "0.30.6"
sql_paginatorr = "0.1.1"
